-- 0007: cross-cutting platform tables — transactional outbox, idempotency,
--       schema migration bookkeeping is separate (see 0000 in the runner).
-- §5.4.

-- ---------------------------------------------------------------------------
-- Transactional outbox (§5.4).
--
-- "Write the domain change and the outbox row in one transaction; a worker
-- publishes."  This is the mechanism that makes 'achievement unlocked exactly
-- once' TRUE rather than merely intended: there is no window in which the
-- domain change is committed but the side effect is lost, and no window in
-- which the side effect fires for a change that rolled back.
--
-- This is also why ADR-005 chose a monolith: a single BEGIN spans both writes.
-- ---------------------------------------------------------------------------
CREATE TABLE outbox (
  id            uuid PRIMARY KEY,
  -- Which module published it — used for routing and for per-module lag metrics.
  module        text NOT NULL,
  event_type    text NOT NULL,
  -- The entity this event is about, for tracing and for replay-by-aggregate.
  aggregate_type text NOT NULL,
  aggregate_id  uuid NOT NULL,
  payload       jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Ordering guarantee is per aggregate, not global.  Global ordering would
  -- serialise the whole system for no benefit.
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'processing', 'published', 'dead')),
  attempts      int  NOT NULL DEFAULT 0,
  -- Exponential backoff with jitter (§5.4); the worker sets this, not a timer.
  next_attempt_at timestamptz(3) NOT NULL DEFAULT now(),
  last_error    text,

  -- Propagated from the originating request so a side effect can be traced
  -- back to the API call that caused it (§14.2).
  trace_id      text,

  created_at    timestamptz(3) NOT NULL DEFAULT now(),
  published_at  timestamptz(3)
);

COMMENT ON TABLE outbox IS
  '§5.4. Domain change + outbox row commit together. This is why exactly-once achievement grants are true and not merely claimed.';

-- Query: "the worker claims the next batch of due rows."  This is the single
-- hottest query in the background tier, so the index is partial and ordered to
-- match it exactly.
CREATE INDEX idx_outbox_due ON outbox (next_attempt_at, id)
  WHERE status = 'pending';

-- Query: "alert when outbox lag exceeds 5 minutes" (§14.2 alert: ticket).
CREATE INDEX idx_outbox_lag ON outbox (created_at)
  WHERE status IN ('pending', 'processing');

-- Query: "dead-letter queue review" (§5.4).
CREATE INDEX idx_outbox_dead ON outbox (created_at DESC)
  WHERE status = 'dead';

-- Query: "replay all events for one aggregate" (achievement backfill, §8.5).
CREATE INDEX idx_outbox_aggregate ON outbox (aggregate_type, aggregate_id, created_at);

-- ---------------------------------------------------------------------------
-- Idempotency (§5.2).
--
-- "Idempotency-Key required on all non-GET mutations. Server stores key ->
-- response for 24h and replays."
--
-- The key is generated by the CLIENT AT ENQUEUE TIME (ADR-008, §11.3), not at
-- send time.  That distinction is the whole point: a request that times out
-- but actually succeeded, then retries, replays the stored response instead of
-- applying twice.
-- ---------------------------------------------------------------------------
CREATE TABLE idempotency_keys (
  -- The client-supplied key, scoped to the user so one user's key cannot
  -- collide with or replay another's.
  user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key           text NOT NULL CHECK (length(key) BETWEEN 8 AND 255),

  -- Guards against a client reusing one key for two different requests. If the
  -- fingerprint differs, that is a client bug and we return 422 rather than
  -- silently replaying the wrong response.
  request_fingerprint bytea NOT NULL,

  endpoint      text NOT NULL,
  status        text NOT NULL DEFAULT 'in_flight'
                  CHECK (status IN ('in_flight', 'completed')),
  response_status int,
  response_body   jsonb,

  created_at    timestamptz(3) NOT NULL DEFAULT now(),
  completed_at  timestamptz(3),
  -- 24h per §5.2.
  expires_at    timestamptz(3) NOT NULL DEFAULT (now() + interval '24 hours'),

  PRIMARY KEY (user_id, key)
);

COMMENT ON COLUMN idempotency_keys.request_fingerprint IS
  'SHA-256 of method+path+body. A key reused with a different body is a client bug -> 422, never a silent wrong replay.';

COMMENT ON COLUMN idempotency_keys.status IS
  'in_flight is inserted BEFORE the handler runs, so two concurrent identical requests serialise on the PK rather than both executing.';

-- Query: "reaper deletes expired keys."
CREATE INDEX idx_idem_expiry ON idempotency_keys (expires_at);

-- ---------------------------------------------------------------------------
-- Feature flags (§5.4): server-evaluated, user-bucketed, with a kill switch
-- for every realtime feature.
-- ---------------------------------------------------------------------------
CREATE TABLE feature_flags (
  key           text PRIMARY KEY,
  description   text NOT NULL,
  -- The kill switch.  When false, the feature is off for everyone regardless
  -- of bucketing.  §14.1 requires one of these per realtime feature.
  enabled       boolean NOT NULL DEFAULT false,
  -- Percentage rollout, bucketed by a stable hash of user_id so a user does
  -- not flip between cohorts on every request.
  rollout_percent int NOT NULL DEFAULT 0 CHECK (rollout_percent BETWEEN 0 AND 100),
  updated_at    timestamptz(3) NOT NULL DEFAULT now(),
  updated_by    uuid REFERENCES users(id) ON DELETE SET NULL
);

CREATE TRIGGER feature_flags_touch BEFORE UPDATE ON feature_flags
  FOR EACH ROW EXECUTE FUNCTION vybe_touch_updated_at();
